version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    networks:
      - app-network

  # If you need a database, for example PostgreSQL, you can add it like this:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: HMS
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
